version: "3.9"

services:
  admin_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adminapi_container
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/admin_service/app  # Match Dockerfile setting
    volumes:
      - .:/admin_service  # Map the entire project directory
    depends_on:
      - db
    networks:
      - custom_network

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Arunnathan
      POSTGRES_DB: admin_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom_network

volumes:
  postgres_data:

networks:
  custom_network:
    driver: bridge
