services:
  admin_service:
    build: .
    container_name: adminapi_container
    command: >
      sh -c "until pg_isready -h db -p 5432; do sleep 2; done &&
             alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - custom_network

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Arunnathan
      POSTGRES_DB: admin_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom_network

volumes:
  postgres_data:
    name: admin_service_postgres_data

networks:
  custom_network:
    name: admin_service_network